import 'package:flutter/material.dart';

import '../../core/models/models.dart';
import '../../core/utils/search_fold.dart';

/// One selectable account glyph and the words that find it. Keywords are stored
/// **per locale-neutral fold** (see [searchAccountIcons]); English and Turkish
/// terms sit side by side so a user typing `araba` and one typing `car` both
/// reach the car icon (spec §5.6).
class AccountIconEntry {
  const AccountIconEntry(this.icon, this.name, this.keywords);

  final IconData icon;
  final String name;
  final List<String> keywords;
}

/// 189 glyphs from the app's shipped Material set, in 13 groups (task 053).
/// Every group holds a multiple of seven, so the picker's seven-column grid
/// never leaves an orphan tile; no glyph appears twice, and no two entries draw
/// the same shape. Every icon here is a `const IconData`.
const Map<String, List<AccountIconEntry>> accountIconGroups = {
  'Banking & cash': [
    AccountIconEntry(Icons.account_balance_rounded, 'Bank', ['bank', 'banka']),
    AccountIconEntry(Icons.account_balance_wallet_rounded, 'Wallet',
        ['wallet', 'cüzdan', 'cuzdan']),
    AccountIconEntry(Icons.payments_rounded, 'Cash', ['cash', 'nakit', 'para']),
    AccountIconEntry(Icons.money_rounded, 'Banknote',
        ['note', 'banknot', 'para']),
    AccountIconEntry(Icons.attach_money_rounded, 'Money',
        ['money', 'para', 'dollar']),
    AccountIconEntry(Icons.euro_rounded, 'Euro', ['euro', 'avro', 'eur']),
    AccountIconEntry(Icons.currency_ruble_rounded, 'Ruble',
        ['ruble', 'rouble', 'rub']),
    AccountIconEntry(Icons.currency_lira_rounded, 'Lira',
        ['lira', 'türk lirası', 'try', 'tl']),
    AccountIconEntry(Icons.currency_pound_rounded, 'Pound',
        ['pound', 'sterling', 'sterlin', 'gbp']),
    AccountIconEntry(Icons.currency_yen_rounded, 'Yen',
        ['yen', 'yuan', 'jpy', 'cny']),
    AccountIconEntry(Icons.currency_exchange_rounded, 'Exchange',
        ['exchange', 'döviz', 'doviz', 'kur']),
    AccountIconEntry(Icons.savings_rounded, 'Piggy bank',
        ['savings', 'kumbara', 'birikim']),
    AccountIconEntry(Icons.atm_rounded, 'ATM', ['atm', 'bankamatik']),
    AccountIconEntry(Icons.toll_rounded, 'Coins',
        ['coins', 'coin', 'gold', 'madeni para', 'bozuk para', 'altın']),
  ],
  'Cards': [
    AccountIconEntry(Icons.credit_card_rounded, 'Credit card',
        ['card', 'kart', 'kredi']),
    AccountIconEntry(Icons.credit_score_rounded, 'Credit score',
        ['credit', 'kredi', 'skor']),
    AccountIconEntry(Icons.add_card_rounded, 'New card',
        ['new card', 'add card', 'yeni kart', 'kart ekle']),
    AccountIconEntry(Icons.credit_card_off_rounded, 'Blocked card',
        ['blocked', 'frozen', 'closed card', 'bloke', 'kapalı kart']),
    AccountIconEntry(Icons.card_membership_rounded, 'Membership',
        ['membership', 'üyelik', 'uyelik']),
    AccountIconEntry(Icons.card_giftcard_rounded, 'Gift card',
        ['gift', 'hediye', 'kart']),
    AccountIconEntry(Icons.local_atm_rounded, 'Cash card',
        ['card', 'kart', 'atm']),
    AccountIconEntry(Icons.contactless_rounded, 'Contactless',
        ['contactless', 'temassız', 'temassiz']),
    AccountIconEntry(Icons.nfc_rounded, 'NFC', ['nfc', 'tap', 'temassız']),
    AccountIconEntry(Icons.point_of_sale_rounded, 'POS',
        ['pos', 'terminal', 'card reader', 'yazar kasa', 'kasa']),
    AccountIconEntry(Icons.qr_code_2_rounded, 'QR pay',
        ['qr', 'qr code', 'karekod', 'qr ödeme']),
    AccountIconEntry(Icons.discount_rounded, 'Cashback',
        ['cashback', 'discount', 'indirim', 'para iadesi']),
    AccountIconEntry(Icons.sim_card_rounded, 'Mobile balance',
        ['mobile', 'sim', 'top up', 'kontör', 'mobil bakiye']),
    AccountIconEntry(Icons.wallet_rounded, 'Card wallet',
        ['card wallet', 'wallet', 'kart cüzdanı', 'cüzdan']),
  ],
  'Receivables & payables': [
    AccountIconEntry(Icons.person_rounded, 'Person',
        ['person', 'kişi', 'kisi']),
    AccountIconEntry(Icons.people_rounded, 'People',
        ['people', 'insanlar', 'aile']),
    AccountIconEntry(Icons.family_restroom_rounded, 'Family',
        ['family', 'relatives', 'aile', 'akraba']),
    AccountIconEntry(Icons.person_add_rounded, 'New contact',
        ['new contact', 'add person', 'yeni kişi', 'kişi ekle']),
    AccountIconEntry(Icons.contacts_rounded, 'Contacts',
        ['contacts', 'contact', 'rehber', 'kişiler']),
    AccountIconEntry(Icons.storefront_rounded, 'Shop',
        ['shop', 'store', 'customer', 'dükkan', 'mağaza', 'müşteri']),
    AccountIconEntry(Icons.business_rounded, 'Company',
        ['company', 'business', 'firm', 'cari', 'şirket', 'firma']),
    AccountIconEntry(Icons.factory_rounded, 'Factory',
        ['factory', 'manufacturer', 'fabrika', 'üretici']),
    AccountIconEntry(Icons.local_shipping_rounded, 'Supplier',
        ['supplier', 'vendor', 'delivery', 'tedarikçi', 'toptancı', 'kargo']),
    AccountIconEntry(Icons.handshake_rounded, 'Deal',
        ['deal', 'anlaşma', 'anlasma', 'el sıkışma']),
    AccountIconEntry(Icons.real_estate_agent_rounded, 'Landlord',
        ['landlord', 'tenant', 'rent', 'ev sahibi', 'kiracı', 'kira']),
    AccountIconEntry(Icons.money_off_rounded, 'Debt',
        ['debt', 'owe', 'cari', 'borç', 'veresiye']),
    AccountIconEntry(Icons.request_quote_rounded, 'Invoice',
        ['invoice', 'fatura', 'teklif']),
    AccountIconEntry(Icons.receipt_long_rounded, 'Receipt',
        ['receipt', 'fiş', 'fis', 'makbuz']),
    AccountIconEntry(Icons.description_rounded, 'Document',
        ['document', 'contract', 'belge', 'sözleşme', 'evrak']),
    AccountIconEntry(Icons.call_received_rounded, 'Money in',
        ['money in', 'receivable', 'incoming', 'cari', 'alacak', 'tahsilat', 'gelen']),
    AccountIconEntry(Icons.call_made_rounded, 'Money out',
        ['money out', 'payable', 'outgoing', 'cari', 'verecek', 'ödeme', 'giden']),
    AccountIconEntry(Icons.pending_actions_rounded, 'Pending',
        ['pending', 'waiting', 'bekleyen', 'beklemede']),
    AccountIconEntry(Icons.event_rounded, 'Due date',
        ['due date', 'deadline', 'calendar', 'vade', 'son ödeme', 'takvim']),
    AccountIconEntry(Icons.balance_rounded, 'Settlement',
        ['settlement', 'reconcile', 'balance', 'cari', 'mahsup', 'hesaplaşma']),
    AccountIconEntry(Icons.gavel_rounded, 'Legal',
        ['legal', 'court', 'lawyer', 'hukuk', 'avukat', 'mahkeme']),
  ],
  'Work & income': [
    AccountIconEntry(Icons.work_rounded, 'Work',
        ['work', 'iş', 'is', 'çalışma']),
    AccountIconEntry(Icons.badge_rounded, 'Badge',
        ['badge', 'kimlik', 'personel']),
    AccountIconEntry(Icons.laptop_rounded, 'Freelance',
        ['freelance', 'laptop', 'bilgisayar']),
    AccountIconEntry(Icons.corporate_fare_rounded, 'Office',
        ['office', 'workplace', 'ofis', 'büro', 'işyeri']),
    AccountIconEntry(Icons.engineering_rounded, 'Engineering',
        ['engineering', 'engineer', 'mühendis', 'mühendislik']),
    AccountIconEntry(Icons.construction_rounded, 'Construction',
        ['construction', 'builder', 'tools', 'inşaat', 'usta']),
    AccountIconEntry(Icons.agriculture_rounded, 'Farming',
        ['farming', 'farm', 'tractor', 'tarım', 'çiftlik', 'traktör']),
    AccountIconEntry(Icons.inventory_2_rounded, 'Stock',
        ['stock', 'inventory', 'goods', 'stok', 'envanter', 'mal']),
    AccountIconEntry(Icons.price_check_rounded, 'Paycheck',
        ['paycheck', 'salary', 'wage', 'maaş', 'ücret', 'bordro']),
    AccountIconEntry(Icons.emoji_events_rounded, 'Bonus',
        ['bonus', 'award', 'prize', 'prim', 'ödül', 'ikramiye']),
    AccountIconEntry(Icons.rocket_launch_rounded, 'Startup',
        ['startup', 'launch', 'project', 'girişim', 'proje']),
    AccountIconEntry(Icons.schedule_rounded, 'Hourly',
        ['hourly', 'shift', 'time', 'saatlik', 'vardiya', 'mesai']),
    AccountIconEntry(Icons.support_agent_rounded, 'Support',
        ['support', 'call center', 'service', 'destek', 'çağrı merkezi', 'hizmet']),
    AccountIconEntry(Icons.videocam_rounded, 'Content',
        ['content', 'video', 'youtube', 'blogger', 'içerik']),
  ],
  'Home & bills': [
    AccountIconEntry(Icons.home_rounded, 'Home', ['home', 'house', 'ev']),
    AccountIconEntry(Icons.apartment_rounded, 'Apartment',
        ['apartment', 'daire', 'apartman']),
    AccountIconEntry(Icons.home_work_rounded, 'Rent', ['rent', 'kira', 'ev']),
    AccountIconEntry(Icons.key_rounded, 'Keys',
        ['keys', 'key', 'deposit', 'anahtar', 'depozito']),
    AccountIconEntry(Icons.bolt_rounded, 'Electricity',
        ['electricity', 'elektrik', 'fatura']),
    AccountIconEntry(Icons.water_drop_rounded, 'Water',
        ['water', 'su', 'fatura']),
    AccountIconEntry(Icons.local_fire_department_rounded, 'Gas',
        ['gas', 'gaz', 'doğalgaz', 'dogalgaz']),
    AccountIconEntry(Icons.wifi_rounded, 'Internet',
        ['internet', 'wifi', 'net']),
    AccountIconEntry(Icons.phone_iphone_rounded, 'Phone', ['phone', 'telefon']),
    AccountIconEntry(Icons.cleaning_services_rounded, 'Cleaning',
        ['cleaning', 'temizlik']),
    AccountIconEntry(Icons.build_rounded, 'Repairs',
        ['repairs', 'repair', 'fix', 'tamir', 'onarım', 'tadilat']),
    AccountIconEntry(Icons.chair_rounded, 'Furniture',
        ['furniture', 'mobilya', 'koltuk']),
    AccountIconEntry(Icons.bed_rounded, 'Bedroom',
        ['bedroom', 'bed', 'yatak', 'yatak odası']),
    AccountIconEntry(Icons.kitchen_rounded, 'Appliances',
        ['appliances', 'fridge', 'kitchen', 'beyaz eşya', 'buzdolabı', 'mutfak']),
  ],
  'Transport': [
    AccountIconEntry(Icons.directions_car_rounded, 'Car',
        ['car', 'araba', 'oto']),
    AccountIconEntry(Icons.local_taxi_rounded, 'Taxi', ['taxi', 'taksi']),
    AccountIconEntry(Icons.directions_bus_rounded, 'Bus',
        ['bus', 'otobüs', 'otobus']),
    AccountIconEntry(Icons.train_rounded, 'Train', ['train', 'tren']),
    AccountIconEntry(Icons.flight_rounded, 'Flight',
        ['flight', 'uçak', 'ucak', 'uçuş']),
    AccountIconEntry(Icons.two_wheeler_rounded, 'Motorbike',
        ['motorbike', 'motosiklet', 'motor']),
    AccountIconEntry(Icons.pedal_bike_rounded, 'Bike', ['bike', 'bisiklet']),
    AccountIconEntry(Icons.electric_scooter_rounded, 'Scooter',
        ['scooter', 'e-scooter', 'skuter']),
    AccountIconEntry(Icons.airport_shuttle_rounded, 'Van',
        ['van', 'minibus', 'shuttle', 'minibüs', 'kamyonet', 'servis']),
    AccountIconEntry(Icons.local_gas_station_rounded, 'Fuel',
        ['fuel', 'benzin', 'yakıt', 'yakit']),
    AccountIconEntry(Icons.ev_station_rounded, 'EV charging',
        ['ev', 'charging', 'electric car', 'şarj', 'elektrikli araç']),
    AccountIconEntry(Icons.local_parking_rounded, 'Parking',
        ['parking', 'otopark']),
    AccountIconEntry(Icons.car_repair_rounded, 'Car service',
        ['car service', 'mechanic', 'servis', 'oto tamir', 'bakım']),
    AccountIconEntry(Icons.traffic_rounded, 'Traffic',
        ['traffic', 'fine', 'ticket', 'trafik', 'ceza']),
  ],
  'Food & shopping': [
    AccountIconEntry(Icons.shopping_cart_rounded, 'Groceries',
        ['groceries', 'market', 'alışveriş', 'alisveris']),
    AccountIconEntry(Icons.shopping_basket_rounded, 'Basket',
        ['basket', 'sepet', 'market']),
    AccountIconEntry(Icons.shopping_bag_rounded, 'Shopping',
        ['shopping', 'alışveriş', 'alisveris', 'çanta']),
    AccountIconEntry(Icons.checkroom_rounded, 'Clothes',
        ['clothes', 'clothing', 'fashion', 'giyim', 'kıyafet', 'elbise']),
    AccountIconEntry(Icons.restaurant_rounded, 'Restaurant',
        ['restaurant', 'restoran', 'yemek']),
    AccountIconEntry(Icons.local_cafe_rounded, 'Cafe',
        ['cafe', 'kafe', 'kahve']),
    AccountIconEntry(Icons.fastfood_rounded, 'Fast food',
        ['food', 'yemek', 'fast food']),
    AccountIconEntry(Icons.local_pizza_rounded, 'Pizza', ['pizza']),
    AccountIconEntry(Icons.bakery_dining_rounded, 'Bakery',
        ['bakery', 'bread', 'pastry', 'fırın', 'ekmek', 'pastane']),
    AccountIconEntry(Icons.ramen_dining_rounded, 'Noodles',
        ['noodles', 'ramen', 'soup', 'erişte', 'çorba']),
    AccountIconEntry(Icons.kebab_dining_rounded, 'Kebab',
        ['kebab', 'grill', 'bbq', 'kebap', 'mangal', 'şiş']),
    AccountIconEntry(Icons.icecream_rounded, 'Ice cream',
        ['ice cream', 'dessert', 'dondurma', 'tatlı']),
    AccountIconEntry(Icons.liquor_rounded, 'Drinks',
        ['drinks', 'içki', 'icki']),
    AccountIconEntry(Icons.local_florist_rounded, 'Flowers',
        ['flowers', 'florist', 'çiçek', 'çiçekçi']),
  ],
  'Health': [
    AccountIconEntry(Icons.favorite_rounded, 'Health',
        ['health', 'sağlık', 'saglik']),
    AccountIconEntry(Icons.local_hospital_rounded, 'Hospital',
        ['hospital', 'hastane', 'sağlık']),
    AccountIconEntry(Icons.medical_services_rounded, 'Doctor',
        ['doctor', 'doktor', 'sağlık']),
    AccountIconEntry(Icons.medication_rounded, 'Pharmacy',
        ['pharmacy', 'eczane', 'ilaç', 'ilac']),
    AccountIconEntry(Icons.vaccines_rounded, 'Vaccines',
        ['vaccine', 'injection', 'aşı', 'iğne']),
    AccountIconEntry(Icons.monitor_heart_rounded, 'Checkup',
        ['checkup', 'heart', 'cardio', 'kontrol', 'check-up', 'kalp']),
    AccountIconEntry(Icons.healing_rounded, 'First aid',
        ['first aid', 'bandage', 'ilk yardım', 'yara bandı']),
    AccountIconEntry(Icons.psychology_rounded, 'Therapy',
        ['therapy', 'psychologist', 'mental', 'terapi', 'psikolog']),
    AccountIconEntry(Icons.pregnant_woman_rounded, 'Maternity',
        ['maternity', 'pregnancy', 'baby', 'hamilelik', 'doğum', 'bebek']),
    AccountIconEntry(Icons.fitness_center_rounded, 'Gym',
        ['gym', 'spor', 'fitness']),
    AccountIconEntry(Icons.sports_soccer_rounded, 'Sports',
        ['sports', 'football', 'soccer', 'spor', 'futbol']),
    AccountIconEntry(Icons.pool_rounded, 'Pool',
        ['pool', 'swimming', 'havuz', 'yüzme']),
    AccountIconEntry(Icons.spa_rounded, 'Wellness',
        ['spa', 'bakım', 'bakim', 'wellness']),
    AccountIconEntry(Icons.self_improvement_rounded, 'Personal',
        ['personal', 'kişisel', 'kisisel', 'yoga']),
  ],
  'Education': [
    AccountIconEntry(Icons.school_rounded, 'School',
        ['school', 'okul', 'eğitim', 'egitim']),
    AccountIconEntry(Icons.backpack_rounded, 'Backpack',
        ['backpack', 'school bag', 'okul çantası', 'sırt çantası']),
    AccountIconEntry(Icons.menu_book_rounded, 'Books',
        ['books', 'kitap', 'ders']),
    AccountIconEntry(Icons.local_library_rounded, 'Library',
        ['library', 'kütüphane']),
    AccountIconEntry(Icons.history_edu_rounded, 'Essay',
        ['essay', 'history', 'homework', 'writing', 'ödev', 'tarih', 'kompozisyon']),
    AccountIconEntry(Icons.edit_rounded, 'Study',
        ['study', 'çalışma', 'calisma', 'ödev']),
    AccountIconEntry(Icons.calculate_rounded, 'Maths',
        ['maths', 'math', 'calculator', 'matematik', 'hesap makinesi']),
    AccountIconEntry(Icons.science_rounded, 'Science',
        ['science', 'bilim', 'laboratuvar']),
    AccountIconEntry(Icons.translate_rounded, 'Languages',
        ['languages', 'language', 'translate', 'dil', 'yabancı dil', 'çeviri']),
    AccountIconEntry(Icons.palette_rounded, 'Art',
        ['art', 'painting', 'drawing', 'sanat', 'resim']),
    AccountIconEntry(Icons.piano_rounded, 'Music lessons',
        ['music lessons', 'piano', 'lesson', 'müzik dersi', 'piyano']),
    AccountIconEntry(Icons.workspace_premium_rounded, 'Diploma',
        ['diploma', 'sertifika', 'başarı']),
    AccountIconEntry(Icons.cast_for_education_rounded, 'Online course',
        ['online course', 'webinar', 'e-learning', 'online eğitim', 'kurs']),
    AccountIconEntry(Icons.quiz_rounded, 'Exams',
        ['exams', 'exam', 'test', 'quiz', 'sınav']),
  ],
  'Travel & leisure': [
    AccountIconEntry(Icons.beach_access_rounded, 'Vacation',
        ['vacation', 'tatil', 'plaj']),
    AccountIconEntry(Icons.luggage_rounded, 'Luggage',
        ['luggage', 'bavul', 'valiz']),
    AccountIconEntry(Icons.hotel_rounded, 'Hotel',
        ['hotel', 'otel', 'konaklama']),
    AccountIconEntry(Icons.map_rounded, 'Trip',
        ['trip', 'gezi', 'seyahat', 'harita']),
    AccountIconEntry(Icons.hiking_rounded, 'Hiking',
        ['hiking', 'mountain', 'trekking', 'doğa yürüyüşü', 'dağ']),
    AccountIconEntry(Icons.park_rounded, 'Park', ['park', 'outdoors', 'bahçe']),
    AccountIconEntry(Icons.attractions_rounded, 'Amusement',
        ['amusement', 'theme park', 'fun', 'lunapark', 'eğlence']),
    AccountIconEntry(Icons.movie_rounded, 'Cinema',
        ['cinema', 'sinema', 'film']),
    AccountIconEntry(Icons.theater_comedy_rounded, 'Theatre',
        ['theatre', 'theater', 'concert', 'tiyatro', 'konser']),
    AccountIconEntry(Icons.music_note_rounded, 'Music',
        ['music', 'müzik', 'muzik']),
    AccountIconEntry(Icons.sports_esports_rounded, 'Games', ['games', 'oyun']),
    AccountIconEntry(Icons.local_activity_rounded, 'Tickets',
        ['tickets', 'ticket', 'event', 'bilet', 'etkinlik']),
    AccountIconEntry(Icons.casino_rounded, 'Casino',
        ['casino', 'lottery', 'betting', 'kumar', 'piyango', 'loto']),
    AccountIconEntry(Icons.celebration_rounded, 'Party',
        ['party', 'parti', 'kutlama']),
  ],
  'Investments & savings': [
    AccountIconEntry(Icons.trending_up_rounded, 'Growth',
        ['growth', 'yatırım', 'yatirim', 'artış']),
    AccountIconEntry(Icons.show_chart_rounded, 'Stocks',
        ['stocks', 'hisse', 'borsa']),
    AccountIconEntry(Icons.candlestick_chart_rounded, 'Trading',
        ['trading', 'borsa', 'işlem', 'islem']),
    AccountIconEntry(Icons.bar_chart_rounded, 'Statistics',
        ['statistics', 'bar chart', 'istatistik', 'grafik']),
    AccountIconEntry(Icons.pie_chart_rounded, 'Portfolio',
        ['portfolio', 'portföy', 'portfoy', 'dağılım']),
    AccountIconEntry(Icons.query_stats_rounded, 'Research',
        ['research', 'analysis', 'araştırma', 'analiz']),
    AccountIconEntry(Icons.monetization_on_rounded, 'Dividends',
        ['dividends', 'dividend', 'payout', 'temettü', 'kâr payı']),
    AccountIconEntry(Icons.currency_bitcoin_rounded, 'Crypto',
        ['crypto', 'bitcoin', 'kripto']),
    AccountIconEntry(Icons.percent_rounded, 'Interest',
        ['interest', 'percent', 'rate', 'faiz', 'yüzde', 'oran']),
    AccountIconEntry(Icons.price_change_rounded, 'Rates',
        ['rates', 'exchange rate', 'price change', 'kur', 'fiyat değişimi']),
    AccountIconEntry(Icons.shield_rounded, 'Insurance',
        ['insurance', 'protection', 'sigorta', 'kasko']),
    AccountIconEntry(Icons.hourglass_bottom_rounded, 'Term deposit',
        ['term deposit', 'deposit', 'fixed', 'vadeli', 'mevduat']),
    AccountIconEntry(Icons.elderly_rounded, 'Pension',
        ['pension', 'emeklilik', 'bes', 'birikim']),
    AccountIconEntry(Icons.account_tree_rounded, 'Holdings',
        ['holdings', 'structure', 'holding', 'iştirak']),
  ],
  'Property & valuables': [
    AccountIconEntry(Icons.villa_rounded, 'Property',
        ['property', 'emlak', 'ev', 'villa']),
    AccountIconEntry(Icons.holiday_village_rounded, 'Holiday home',
        ['holiday home', 'summer house', 'cottage', 'yazlık', 'dağ evi']),
    AccountIconEntry(Icons.garage_rounded, 'Garage', ['garage', 'garaj']),
    AccountIconEntry(Icons.landscape_rounded, 'Land',
        ['land', 'arsa', 'arazi']),
    AccountIconEntry(Icons.directions_boat_rounded, 'Boat',
        ['boat', 'tekne', 'yat']),
    AccountIconEntry(Icons.diamond_rounded, 'Jewellery',
        ['jewellery', 'mücevher', 'mucevher', 'elmas']),
    AccountIconEntry(Icons.watch_rounded, 'Watch',
        ['watch', 'saat', 'kol saati']),
    AccountIconEntry(Icons.devices_rounded, 'Electronics',
        ['electronics', 'elektronik', 'bilgisayar']),
    AccountIconEntry(Icons.tv_rounded, 'TV',
        ['tv', 'television', 'televizyon']),
    AccountIconEntry(Icons.camera_alt_rounded, 'Camera',
        ['camera', 'kamera', 'fotoğraf']),
    AccountIconEntry(Icons.headphones_rounded, 'Headphones',
        ['headphones', 'audio', 'kulaklık']),
    AccountIconEntry(Icons.brush_rounded, 'Artwork',
        ['artwork', 'painting', 'tablo', 'sanat eseri']),
    AccountIconEntry(Icons.collections_rounded, 'Collection',
        ['collection', 'collectibles', 'koleksiyon']),
    AccountIconEntry(Icons.toys_rounded, 'Toys', ['toys', 'toy', 'oyuncak']),
  ],
  'Other': [
    AccountIconEntry(Icons.category_rounded, 'General',
        ['general', 'genel', 'diğer', 'diger']),
    AccountIconEntry(Icons.star_rounded, 'Star',
        ['star', 'yıldız', 'yildiz', 'favori']),
    AccountIconEntry(Icons.flag_rounded, 'Goal', ['goal', 'hedef', 'amaç']),
    AccountIconEntry(Icons.lightbulb_rounded, 'Idea',
        ['idea', 'fikir', 'proje']),
    AccountIconEntry(Icons.bookmark_rounded, 'Bookmark',
        ['bookmark', 'saved', 'yer imi', 'kaydet']),
    AccountIconEntry(Icons.push_pin_rounded, 'Pin',
        ['pin', 'pinned', 'sabitle', 'iğne']),
    AccountIconEntry(Icons.pets_rounded, 'Pets', ['pets', 'evcil', 'hayvan']),
    AccountIconEntry(Icons.child_care_rounded, 'Kids',
        ['kids', 'çocuk', 'cocuk']),
    AccountIconEntry(Icons.cake_rounded, 'Birthday',
        ['birthday', 'cake', 'doğum günü', 'pasta']),
    AccountIconEntry(Icons.volunteer_activism_rounded, 'Charity',
        ['charity', 'bağış', 'bagis', 'yardım']),
    AccountIconEntry(Icons.mosque_rounded, 'Mosque',
        ['mosque', 'religion', 'zakat', 'cami', 'zekat', 'sadaka']),
    AccountIconEntry(Icons.public_rounded, 'World',
        ['world', 'global', 'abroad', 'dünya', 'yurt dışı']),
    AccountIconEntry(Icons.grass_rounded, 'Nature',
        ['nature', 'plants', 'garden', 'doğa', 'bitki']),
    AccountIconEntry(Icons.extension_rounded, 'Misc',
        ['misc', 'other', 'various', 'çeşitli', 'diğer']),
  ],
};

/// Six suggestion glyphs for the inline row, keyed to the group (spec §5.5).
List<IconData> iconSuggestionsFor(AccountGroup group) {
  switch (group) {
    case AccountGroup.spendable:
      return const [
        Icons.account_balance_rounded,
        Icons.payments_rounded,
        Icons.account_balance_wallet_rounded,
        Icons.people_rounded,
        Icons.savings_rounded,
        Icons.attach_money_rounded,
      ];
    case AccountGroup.setAside:
      // Saving-toward-a-goal cash — never a lock/padlock; the money is not
      // restricted, only mentally reserved.
      return const [
        Icons.savings_rounded,
        Icons.flag_rounded,
        Icons.card_giftcard_rounded,
        Icons.volunteer_activism_rounded,
        Icons.account_balance_wallet_rounded,
        Icons.attach_money_rounded,
      ];
    case AccountGroup.receivables:
      return const [
        Icons.handshake_rounded,
        Icons.receipt_long_rounded,
        Icons.request_quote_rounded,
        Icons.person_rounded,
        Icons.schedule_rounded,
        Icons.call_received_rounded,
      ];
    case AccountGroup.investments:
      return const [
        Icons.trending_up_rounded,
        Icons.show_chart_rounded,
        Icons.currency_bitcoin_rounded,
        Icons.toll_rounded,
        Icons.pie_chart_rounded,
        Icons.savings_rounded,
      ];
    case AccountGroup.valuables:
      return const [
        Icons.diamond_rounded,
        Icons.home_rounded,
        Icons.directions_car_rounded,
        Icons.watch_rounded,
        Icons.devices_rounded,
        Icons.landscape_rounded,
      ];
    case AccountGroup.creditCards:
      return const [
        Icons.credit_card_rounded,
        Icons.contactless_rounded,
        Icons.shopping_bag_rounded,
        Icons.card_membership_rounded,
        Icons.add_card_rounded,
        Icons.card_giftcard_rounded,
      ];
    case AccountGroup.payables:
      return const [
        Icons.description_rounded,
        Icons.home_work_rounded,
        Icons.bolt_rounded,
        Icons.wifi_rounded,
        Icons.water_drop_rounded,
        Icons.receipt_long_rounded,
      ];
    case AccountGroup.bankLoans:
      return const [
        Icons.account_balance_rounded,
        Icons.apartment_rounded,
        Icons.directions_car_rounded,
        Icons.school_rounded,
        Icons.work_rounded,
        Icons.home_rounded,
      ];
  }
}

/// The default glyph chosen the instant a group is picked (spec §5.5).
IconData defaultIconFor(AccountGroup group) => iconSuggestionsFor(group).first;

/// Best-effort Russian + Turkmen search terms for the catalog, keyed by the
/// entry's English [AccountIconEntry.name] (spec §7b; task 053 extends it to
/// all 189 entries). Folded into [searchAccountIcons] at query time.
const Map<String, List<String>> _ruTkIconTerms = {
  'Bank': ['банк', 'bank'],
  'Wallet': ['кошелёк', 'gapjyk'],
  'Cash': ['наличные', 'nagt'],
  'Banknote': ['банкнота', 'pul'],
  'Money': ['деньги', 'pul'],
  'Euro': ['евро', 'ýewro'],
  'Ruble': ['рубль', 'rubl'],
  'Lira': ['лира', 'lira'],
  'Pound': ['фунт', 'funt'],
  'Yen': ['иена', 'юань', 'ýen', 'ýuan'],
  'Exchange': ['обмен', 'çalyşma', 'kurs'],
  'Piggy bank': ['копилка', 'gazna'],
  'ATM': ['банкомат', 'bankomat'],
  'Coins': ['монеты', 'золото', 'teňňe', 'altyn'],
  'Credit card': ['карта', 'kart'],
  'Credit score': ['кредит', 'karz'],
  'New card': ['новая карта', 'täze kart'],
  'Blocked card': ['заблокирована', 'bloklanan kart'],
  'Membership': ['членство', 'agzalyk'],
  'Gift card': ['подарок', 'sowgat'],
  'Cash card': ['карта', 'kart'],
  'Contactless': ['бесконтакт', 'galtaşyksyz'],
  'NFC': ['бесконтакт', 'nfc'],
  'POS': ['терминал', 'kassa'],
  'QR pay': ['qr код', 'qr töleg'],
  'Cashback': ['кэшбэк', 'скидка', 'arzanladyş'],
  'Mobile balance': ['мобильный', 'баланс', 'mobil', 'balans'],
  'Card wallet': ['кошелёк', 'gapjyk'],
  'Person': ['человек', 'adam'],
  'People': ['люди', 'adamlar', 'maşgala'],
  'Family': ['семья', 'maşgala', 'garyndaş'],
  'New contact': ['новый контакт', 'täze adam'],
  'Contacts': ['контакты', 'kontaktlar'],
  'Shop': ['магазин', 'клиент', 'dükan', 'müşderi'],
  'Company': ['компания', 'фирма', 'kompaniýa', 'firma'],
  'Factory': ['завод', 'фабрика', 'zawod', 'fabrik'],
  'Supplier': ['поставщик', 'üpjün ediji'],
  'Deal': ['сделка', 'ylalaşyk'],
  'Landlord': ['арендодатель', 'арендатор', 'jaý eýesi', 'kärende'],
  'Debt': ['долг', 'bergi', 'karz'],
  'Invoice': ['счёт', 'hasap'],
  'Receipt': ['чек', 'kwitansiýa'],
  'Document': ['документ', 'договор', 'resminama', 'şertnama'],
  'Money in': ['приход', 'дебиторка', 'algy', 'girdeji'],
  'Money out': ['расход', 'кредиторка', 'bergi', 'töleg'],
  'Pending': ['ожидание', 'garaşylýar'],
  'Due date': ['срок', 'календарь', 'möhlet', 'senenama'],
  'Settlement': ['расчёт', 'сверка', 'hasaplaşyk'],
  'Legal': ['суд', 'юрист', 'kazyýet', 'hukuk'],
  'Work': ['работа', 'iş'],
  'Badge': ['пропуск', 'şahsyýetnama'],
  'Freelance': ['фриланс', 'kompýuter'],
  'Office': ['офис', 'ofis'],
  'Engineering': ['инженер', 'inžener'],
  'Construction': ['стройка', 'gurluşyk', 'ussa'],
  'Farming': ['ферма', 'сельское хозяйство', 'daýhan', 'oba hojalygy'],
  'Stock': ['склад', 'товар', 'ammar', 'haryt'],
  'Paycheck': ['зарплата', 'aýlyk', 'zähmet haky'],
  'Bonus': ['премия', 'baýrak', 'sylag'],
  'Startup': ['стартап', 'taslama'],
  'Hourly': ['почасовая', 'смена', 'sagatlaýyn', 'smena'],
  'Support': ['поддержка', 'goldaw', 'hyzmat'],
  'Content': ['контент', 'видео', 'wideo', 'mazmun'],
  'Home': ['дом', 'öý'],
  'Apartment': ['квартира', 'jaý'],
  'Rent': ['аренда', 'kärende', 'kira'],
  'Keys': ['ключи', 'açar'],
  'Electricity': ['электричество', 'elektrik'],
  'Water': ['вода', 'suw'],
  'Gas': ['газ', 'gaz'],
  'Internet': ['интернет', 'internet'],
  'Phone': ['телефон', 'telefon'],
  'Cleaning': ['уборка', 'arassaçylyk'],
  'Repairs': ['ремонт', 'abatlaýyş', 'bejeriş'],
  'Furniture': ['мебель', 'mebel'],
  'Bedroom': ['спальня', 'кровать', 'ýatylýan otag', 'krowat'],
  'Appliances': ['техника', 'холодильник', 'tehnika', 'sowadyjy'],
  'Car': ['машина', 'awtoulag', 'ulag'],
  'Taxi': ['такси', 'taksi'],
  'Bus': ['автобус', 'awtobus'],
  'Train': ['поезд', 'otly'],
  'Flight': ['самолёт', 'uçar', 'uçuş'],
  'Motorbike': ['мотоцикл', 'motosikl'],
  'Bike': ['велосипед', 'welosiped'],
  'Scooter': ['самокат', 'samokat'],
  'Van': ['микроавтобус', 'marşrutka'],
  'Fuel': ['бензин', 'ýangyç'],
  'EV charging': ['зарядка', 'электромобиль', 'zarýad'],
  'Parking': ['парковка', 'awtoduralga'],
  'Car service': ['автосервис', 'awtoserwis', 'ussahana'],
  'Traffic': ['штраф', 'jerime', 'ýol hereketi'],
  'Groceries': ['продукты', 'bazar'],
  'Basket': ['корзина', 'sebet'],
  'Shopping': ['покупки', 'söwda'],
  'Clothes': ['одежда', 'egin-eşik', 'geýim'],
  'Restaurant': ['ресторан', 'restoran', 'nahar'],
  'Cafe': ['кафе', 'kafe', 'kofe'],
  'Fast food': ['фастфуд', 'çalt nahar'],
  'Pizza': ['пицца', 'pissa'],
  'Bakery': ['пекарня', 'хлеб', 'çörek', 'tamdyr'],
  'Noodles': ['лапша', 'суп', 'unaş', 'çorba'],
  'Kebab': ['шашлык', 'кебаб', 'kebap', 'şaşlyk'],
  'Ice cream': ['мороженое', 'doňdurma', 'süýji'],
  'Drinks': ['напитки', 'içgi'],
  'Flowers': ['цветы', 'gül', 'güller'],
  'Health': ['здоровье', 'saglyk'],
  'Hospital': ['больница', 'keselhana'],
  'Doctor': ['врач', 'lukman'],
  'Pharmacy': ['аптека', 'derman'],
  'Vaccines': ['прививка', 'sanjym', 'waksina'],
  'Checkup': ['обследование', 'сердце', 'barlag', 'ýürek'],
  'First aid': ['первая помощь', 'ilkinji kömek'],
  'Therapy': ['терапия', 'психолог', 'psiholog'],
  'Maternity': ['беременность', 'роды', 'göwrelilik', 'çaga'],
  'Gym': ['спортзал', 'sport'],
  'Sports': ['спорт', 'футбол', 'sport', 'futbol'],
  'Pool': ['бассейн', 'basseýn', 'ýüzmek'],
  'Wellness': ['спа', 'dynç'],
  'Personal': ['личное', 'şahsy'],
  'School': ['школа', 'mekdep', 'okuw'],
  'Backpack': ['рюкзак', 'arka torba'],
  'Books': ['книги', 'kitap'],
  'Library': ['библиотека', 'kitaphana'],
  'Essay': ['сочинение', 'история', 'taryh', 'öý işi'],
  'Study': ['учёба', 'okuw'],
  'Maths': ['математика', 'калькулятор', 'matematika', 'kalkulýator'],
  'Science': ['наука', 'ylym'],
  'Languages': ['языки', 'перевод', 'dil', 'terjime'],
  'Art': ['искусство', 'рисование', 'sungat', 'surat'],
  'Music lessons': ['уроки музыки', 'пианино', 'saz sapagy', 'pianino'],
  'Diploma': ['диплом', 'diplom'],
  'Online course': ['онлайн курс', 'onlaýn kurs'],
  'Exams': ['экзамены', 'synag'],
  'Vacation': ['отпуск', 'dynç alyş', 'plaj'],
  'Luggage': ['багаж', 'ýük'],
  'Hotel': ['отель', 'myhmanhana'],
  'Trip': ['поездка', 'syýahat'],
  'Hiking': ['поход', 'горы', 'dag', 'gezelenç'],
  'Park': ['парк', 'seýilgäh'],
  'Amusement': ['аттракционы', 'attraksion', 'güýmenje'],
  'Cinema': ['кино', 'kino', 'film'],
  'Theatre': ['театр', 'концерт', 'teatr', 'konsert'],
  'Music': ['музыка', 'saz'],
  'Games': ['игры', 'oýun'],
  'Tickets': ['билеты', 'bilet'],
  'Casino': ['казино', 'лотерея', 'lotereýa'],
  'Party': ['вечеринка', 'baýramçylyk'],
  'Growth': ['рост', 'ösüş'],
  'Stocks': ['акции', 'paýlar', 'birža'],
  'Trading': ['трейдинг', 'söwda'],
  'Statistics': ['статистика', 'statistika'],
  'Portfolio': ['портфель', 'portfel'],
  'Research': ['анализ', 'derňew', 'analiz'],
  'Dividends': ['дивиденды', 'diwidend'],
  'Crypto': ['крипто', 'kripto'],
  'Interest': ['проценты', 'göterim'],
  'Rates': ['курс', 'kurs', 'baha'],
  'Insurance': ['страховка', 'ätiýaçlandyryş'],
  'Term deposit': ['вклад', 'депозит', 'goýum', 'depozit'],
  'Pension': ['пенсия', 'pensiýa'],
  'Holdings': ['холдинг', 'holding'],
  'Property': ['недвижимость', 'emläk'],
  'Holiday home': ['дача', 'daça', 'bag jaý'],
  'Garage': ['гараж', 'garaž'],
  'Land': ['земля', 'ýer'],
  'Boat': ['лодка', 'gämi'],
  'Jewellery': ['украшения', 'şaý-sepler'],
  'Watch': ['часы', 'sagat'],
  'Electronics': ['электроника', 'elektronika'],
  'TV': ['телевизор', 'telewizor'],
  'Camera': ['камера', 'kamera'],
  'Headphones': ['наушники', 'nauşnik'],
  'Artwork': ['картина', 'surat', 'sungat eseri'],
  'Collection': ['коллекция', 'kolleksiýa'],
  'Toys': ['игрушки', 'oýunjak'],
  'General': ['общее', 'umumy', 'başga'],
  'Star': ['звезда', 'ýyldyz'],
  'Goal': ['цель', 'maksat'],
  'Idea': ['идея', 'pikir'],
  'Bookmark': ['закладка', 'bellik'],
  'Pin': ['булавка', 'berkitmek'],
  'Pets': ['питомец', 'öý haýwany'],
  'Kids': ['дети', 'çagalar'],
  'Birthday': ['день рождения', 'торт', 'doglan gün', 'tort'],
  'Charity': ['благотворительность', 'haýyr-sahawat'],
  'Mosque': ['мечеть', 'закят', 'metjit', 'zekat'],
  'World': ['мир', 'за границей', 'dünýä', 'daşary ýurt'],
  'Nature': ['природа', 'сад', 'tebigat', 'bag'],
  'Misc': ['разное', 'dürli'],
};

/// Filters the catalog by a folded, locale-insensitive match on the icon name,
/// its inline en+tr keywords, and the supplementary ru+tk terms, so `araba`,
/// `car`, `машина` and `awtoulag` all surface the car (spec §5.6 / §7b).
List<AccountIconEntry> searchAccountIcons(String query) {
  final q = foldSearch(query.trim());
  final out = <AccountIconEntry>[];
  for (final entries in accountIconGroups.values) {
    for (final e in entries) {
      final extra = _ruTkIconTerms[e.name] ?? const [];
      final hay = foldSearch([e.name, ...e.keywords, ...extra].join(' '));
      if (q.isEmpty || hay.contains(q)) out.add(e);
    }
  }
  return out;
}
